#!/bin/sh
set -e
echo "state-script version: 1" >&2

OK=0
RETRY_LATER=21

MAPPERS="c8y az aws"

is_mapper_connected() {
    CLOUD_MAPPER="$1"

    if [ -n "$(tedge config get "$CLOUD_MAPPER.url" 2>/dev/null)" ]; then
        tedge connect "$CLOUD_MAPPER" --test >&2
    else
        # If the configuration is not configured, then treat the device as healthy
        echo "Mapper is not configured: $CLOUD_MAPPER" >&2
        return 0
    fi
}

all_healthy() {
    # Check all mappers before returning, and fail if
    # any of the configured mappers are not healthy
    failed=0
    for name in $MAPPERS; do
        if ! is_mapper_connected "$name"; then
            failed=1
        fi
    done

    return "$failed"
}

if ! all_healthy; then
    exit "$RETRY_LATER"
fi

exit "$OK"
