operation = "firmware_update"

[init]
next = ["scheduled"]

[scheduled]
next = ["executing"]

[executing]
script = "/etc/tedge/operations/mender_workflow.sh executing --id ${.topic.cmd_id} --on-success download"
next = ["download"]

[download]
script = "/etc/tedge/operations/mender_workflow.sh download --id ${.topic.cmd_id} --url ${.payload.remoteUrl} --on-success install --on-error failed"
next = ["install"]

[install]
script = "/etc/tedge/operations/mender_workflow.sh install --id ${.topic.cmd_id} --url ${.payload.url} --on-success commit --on-restart restart --on-error failed"
next = ["commit", "restart", "failed"]

[restart]
script = "restart"
next = ["restarting", "restarted", "failed_restart"]

[restarted]
script = "/etc/tedge/operations/mender_workflow.sh restarted --id ${.topic.cmd_id} --on-success commit"
next = ["commit"]

[failed_restart]
script = "/etc/tedge/operations/mender_workflow.sh failed_restart --id ${.topic.cmd_id} --on-success failed --on-error failed"
next = ["failed"]

[commit]
script = "/etc/tedge/operations/mender_workflow.sh commit --id ${.topic.cmd_id} --firmware-name ${.payload.name} --firmware-version ${.payload.version} --url ${.payload.remoteUrl} --on-success successful --on-restart rollback_restart --on-error rollback_restart"
next = ["successful", "rollback_restart"]

[rollback_restart]
script = "restart"
next = ["restarting", "rollback_successful", "failed"]

[rollback_successful]
script = "/etc/tedge/operations/mender_workflow.sh rollback_successful --id ${.topic.cmd_id} --on-success failed"
next = ["failed"]

[successful]
next = []

[failed]
next = []

